language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_script: .travis/setup.pl
script: bundle exec perl Makefile.PL lib=libssh2/lib inc=libss2/include && make test
